name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyter_server
  - pip:
    - jupyterlab-filesystem-access
    - jupyterlite-core==0.1.0b21
    - jupyterlite-xeus-python==0.7.0
